# Generated by Django 5.0 on 2023-12-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_records_actueel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='bodemas_perc',
            field=models.IntegerField(max_length=3),
        ),
    ]
