# Generated by Django 5.0 on 2023-12-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_records_bodemas_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='slagingskans',
            field=models.IntegerField(),
        ),
    ]
